# Generated by Django 5.2.8 on 2025-11-19 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('is_veteran', models.BooleanField(default=False, help_text='シフトに最低1人は必要な場合にチェック', verbose_name='ベテランフラグ')),
                ('max_hours_per_week', models.IntegerField(default=28, verbose_name='週の最大勤務時間')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('start_time', models.IntegerField(choices=[(9, '9:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00'), (22, '22:00'), (23, '23:00')], verbose_name='開始時間(時)')),
                ('end_time', models.IntegerField(choices=[(9, '9:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00'), (22, '22:00'), (23, '23:00')], verbose_name='終了時間(時)')),
                ('availability', models.BooleanField(default=True, verbose_name='出勤可否')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.staff')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('start_time', models.IntegerField(verbose_name='開始時間(時)')),
                ('end_time', models.IntegerField(verbose_name='終了時間(時)')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.staff')),
            ],
        ),
    ]
